name: customer_laundry_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.5.0+1
  equatable: ^2.0.5
  filter_list: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  # flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  logger: ^2.4.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    # - assets/images/img_dummyDiscount1.png
